spring:
  application:
    name: proyecto-pedagogico-mongodb
  
  data:
    mongodb:
      # No especificar host ni port cuando se usa Flapdoodle
      # Flapdoodle configurará automáticamente el puerto
      database: pedagogico_db
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.18

server:
  port: 8083

logging:
  level:
    root: INFO
    com.dam.accesodatos: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
